"""
Challenge 

cons(a, b) constructs a pair, and car(pair) and cdr(pair) returns the first and last element of that pair. For example, car(cons(3, 4)) returns 3, and cdr(cons(3, 4)) returns 4.
Given this implementation of cons:
def cons(a, b):
    def pair(f):
        return f(a, b)
    return pair
Implement car and cdr."""


def cons(a, b):
    def pair(f):
        return f(a, b)
    return pair


def car(pair):
    """ Pair is actually function generated by cons function 
    that takes as parameter another function with same parameters as cons, 
    this function implements function that returns pair functions first parameter and returns its value."""

    def first(a, b):
        return a
    return pair(first)


def cdr(pair):
    """ Same as above just for second value."""

    def second(a, b):
        return b
    return pair(second)


assert car(cons(3, 4)) == 3
assert cdr(cons(3, 4)) == 4
